---
- include_tasks: is_systemd.yml

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure Conflicting NTP-related packages are removed.
  become: yes
  apt:
    name: systemd-timesyncd
    state: absent


- name: Ensure NTP-related packages are installed.
  become: yes
  apt:
    name: ntp
    state: present

- name: Ensure tzdata package is installed (Linux).
  become: yes
  apt:
    name: "{{ ntp_tzdata_package }}"
    state: present
  when: ansible_system == "Linux"

- name: Set timezone
  become: yes
  timezone:
    name: "{{ ntp_timezone }}"


- name: create ntp service instance
  import_role:
    name: micko920.role_createservice
  vars:
    service_list:
      - name: "ntp"
        description: "Network Time Service"
        documentation: "man:ntpd(8)"
        start_command: "/usr/lib/ntp/ntp-systemd-wrapper"
        type: "simple"
        after: "network.target network-online.target"
        requires: "network-online.target"
        extra_values:
          KillMode: "process"
          KillSignal: "SIGQUIT"
          TimeoutStopSec: "5s"
          LimitNOFILE: "1048576"
          LimitNPROC: "512"
  when: systemd_pid_1 is defined and systemd_pid_1

- name: Let Systemd handle PID file
  lineinfile:
    dest: /usr/lib/ntp/ntp-systemd-wrapper
    regexp: "exec \\$DAEMON .*"
    line: "exec $DAEMON $NTPD_OPTS"
  when: systemd_pid_1 is defined and systemd_pid_1


- name: Correct Daemon mode
  lineinfile:
    dest: /etc/default/ntp
    regexp: "NTPD_OPTS=.*"
    line: "NTPD_OPTS='-g -n'"
  when: systemd_pid_1 is defined and systemd_pid_1

- name: Ensure NTP is running and enabled as configured.
  become: yes
  systemd:
    name: "{{ ntp_daemon }}"
    state: started
    enabled: true
  when:
    - ntp_enabled | bool
    - systemd_pid_1 is defined and systemd_pid_1

- name: Ensure NTP is stopped and disabled as configured.
  become: yes
  systemd:
    name: "{{ ntp_daemon }}"
    state: stopped
    enabled: false
  when:
    - not (ntp_enabled | bool)
    - systemd_pid_1 is defined and systemd_pid_1

- name: Generate ntp.conf file
  become: yes
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify: restart ntp
  when: ntp_manage_config | bool
