---
- include_tasks: is_systemd.yml

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure NTP-related packages are installed.
  become: yes
  apt:
    name: ntp
    state: present

- name: Ensure tzdata package is installed (Linux).
  become: yes
  apt:
    name: "{{ ntp_tzdata_package }}"
    state: present
  when: ansible_system == "Linux"

- include_tasks: clock-rhel-6.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_version.split('.')[0] == '6'

- name: Set timezone
  become: yes
  timezone:
    name: "{{ ntp_timezone }}"


- name: Remove unit service file
  file:
    path: /etc/systemd/system/multi-user.target.wants/ntp.service
    state: absent

- name: create ntp service instance
  import_role:
    name: micko920.role_createservice
  vars:
    service_list:
      - name: "ntp"
        description: "Network Time Service"
        documentation: "man:ntpd(8)"
        start_command: "/usr/lib/ntp/ntp-systemd-wrapper"
        type: "forking"
        after: "network.target network-online.target"
        requires: "network-online.target"
        extra_values:
          KillMode: "mixed"
          KillSignal: "SIGQUIT"
          TimeoutStopSec: "5s"
          LimitNOFILE: "1048576"
          LimitNPROC: "512"
  when: systemd_pid_1 is defined and systemd_pid_1


- name: Ensure NTP is running and enabled as configured.
  become: yes
  systemd:
    name: "{{ ntp_daemon }}"
    state: started
    enabled: true
  when:
    - ntp_enabled | bool
    - systemd_pid_1 is defined and systemd_pid_1

- name: Ensure NTP is stopped and disabled as configured.
  become: yes
  systemd:
    name: "{{ ntp_daemon }}"
    state: stopped
    enabled: false
  when:
    - not (ntp_enabled | bool)
    - systemd_pid_1 is defined and systemd_pid_1

- name: Generate ntp.conf file
  become: yes
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify: restart ntp
  when: ntp_manage_config | bool
